apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.project.namespace }}
  annotations:
    "helm.sh/hook": "pre-install,post-delete"
    "helm.sh/hook-weight": "0"  # Ensures it runs before any other resources
  labels:
    app.kubernetes.io/part-of: {{ .Values.project.namespace }}