apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.project.name }}-app-2
spec:
  project: {{ .Values.project.name }}
  destination:
    namespace: {{ .Values.project.namespace }}
    name: {{ .Values.project.clusterName }}
  source:
    repoURL: {{ .Values.infra.gitOpsRepoUrl }}
    path: "gitops/{{ .Values.project.namespace }}/app-2"
    targetRevision: HEAD
  syncPolicy:
{{ .Values.global.syncPolicy | toYaml | indent 4 }}